CREATE TABLE [dbo].[AFL_QTS_MES_DATA]
(
[ORGANIZATION_ID] [int] NOT NULL,
[QTS_MESGUID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_AFL_QTS_MES_DATA_QTS_MESGUID] DEFAULT (newid()),
[WIP_ENTITY_NAME] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PIECE_NUMBER] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TESTING_START_DATE] [datetime] NULL,
[TESTING_END_DATE] [datetime] NULL,
[PASS_FAIL_FLAG] [bit] NULL CONSTRAINT [DF_AFL_QTS_MES_DATA_PASS_FAIL_FLAG] DEFAULT ((0)),
[OVERRIDE] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_AFL_QTS_MES_DATA_OVERIDE] DEFAULT ('N'),
[CREATION_DATE] [datetime] NOT NULL CONSTRAINT [DF_AFL_QTS_MES_DATA_CREATION_DATE] DEFAULT (getdate()),
[CREATED_BY] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LAST_UPDATED_BY] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_UPDATE_DATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AFL_QTS_MES_DATA] ADD CONSTRAINT [PK_AFL_QTS_MES_DATA] PRIMARY KEY CLUSTERED  ([QTS_MESGUID]) ON [PRIMARY]
GO
