CREATE TABLE [dbo].[AFL_MES2O_Interface_Data]
(
[MES_REFERENCE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_AFL_MES2O_Interface_Data_MES_REFERENCE_ID] DEFAULT (newid()),
[BATCH_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DJ_NUMBER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROCESSING_ACTION] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ITEM_NUMBER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANSACTION_QTY] [decimal] (10, 4) NULL,
[MES_PLANT_LOCATION] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MES_MACHINE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIBER_GROUP_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_SEQ_NUMBER] [int] NULL,
[SUBINVENTORY_CODE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCATOR_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FINAL_COMPLETION_FLAG] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOT_NUMBER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FROM_OP_SEQ_NUMBER] [int] NULL,
[FROM_OP_SEQ_STEP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TO_OP_SEQ_NUMBER] [int] NULL,
[TO_OP_SEQ_STEP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTION] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTION_TIME] [datetime] NULL,
[TRANSACTION_DISPOSITION] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATION_DATE] [datetime] NULL,
[LAST_UPDATED_DATE] [datetime] NULL,
[RUN_STATUS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RUN_ID] [int] NULL,
[UNIQUE_ID] [int] NOT NULL IDENTITY(1, 1),
[ERROR_MESSAGE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[AFL_MES2O_Interface_Data_InsertDate] ON [dbo].[AFL_MES2O_Interface_Data]
AFTER INSERT
AS
	UPDATE [dbo].[AFL_MES2O_Interface_Data]
	SET [CREATION_DATE]= GetDate()
	FROM Inserted i
	WHERE [dbo].[AFL_MES2O_Interface_Data].[MES_REFERENCE_ID] = i.[MES_REFERENCE_ID]

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[AFL_MES2O_Interface_Data_UpdateDate] ON [dbo].[AFL_MES2O_Interface_Data]
AFTER UPDATE
AS
	UPDATE [dbo].[AFL_MES2O_Interface_Data]
	SET [LAST_UPDATED_DATE]= GetDate()
	FROM inserted i
	WHERE [dbo].[AFL_MES2O_Interface_Data].[MES_REFERENCE_ID] = i.[MES_REFERENCE_ID]

GO
ALTER TABLE [dbo].[AFL_MES2O_Interface_Data] ADD CONSTRAINT [PK_AFL_MES2O_Interface_Data] PRIMARY KEY CLUSTERED  ([MES_REFERENCE_ID]) ON [PRIMARY]
GO
